OCR:
  DET:
    DET_MODEL_DIR: "/home/chiebotgpuhq/MyCode/python/meter_auto_read/model_weight/ppocr/detec"

  REG:
    REC_MODEL_DIR: "/home/chiebotgpuhq/MyCode/python/meter_auto_read/model_weight/ppocr/reg/2"
    REC_CHAR_TYPE: "en"
    REC_IMAGE_SHAPE: " 3,32,100 "

PT_DET:
  CKPT: "/data/experiments_data/point_weight/3pt.ckpt"

# IMG_DIR: "/data/own_dataset/indoor_meter/debug_test"
# IMG_DIR: "/data/own_dataset/indoor_meter/VA_indoor_meter/change_label/test")
IMG_DIR: "/home/chiebotgpuhq/Share/win_share/22222"
# IMG_DIR: "/data/own_dataset/indoor_meter/自己拍摄_电压表"